# Generated by Django 4.1.3 on 2022-11-21 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_of_the_week', models.TextField(verbose_name='Дни недели')),
                ('task', models.TextField(verbose_name='Описание')),
            ],
        ),
    ]
