# Generated by Django 4.1.3 on 2022-11-21 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timetable',
            options={'verbose_name': 'Расписание', 'verbose_name_plural': 'Расписание'},
        ),
        migrations.AlterField(
            model_name='timetable',
            name='days_of_the_week',
            field=models.CharField(max_length=50, verbose_name='Дни недели'),
        ),
    ]
