# Generated by Django 4.1.3 on 2022-11-29 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_blog_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='time_create',
        ),
    ]
