# Generated by Django 4.1.3 on 2023-01-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_blog_time_create_alter_blog_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=300)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_verificated', models.BooleanField(default=False)),
            ],
        ),
    ]
