# Generated by Django 4.1.5 on 2023-02-11 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_reviews'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
    ]
